services:
    lavalink:
        container_name: lavalink
        image: ghcr.io/lavalink-devs/lavalink:latest-alpine
        restart: unless-stopped
        environment:
            - _JAVA_OPTIONS=-Xmx6G
            - SERVER_PORT=2333
            - LAVALINK_SERVER_PASSWORD=lavalink
        volumes:
            - ./application.yaml:/opt/Lavalink/application.yaml
            - ./plugins/:/opt/Lavalink/plugins/

    music-bot:
        container_name: music-bot
        image: ghcr.io/ljstadler/music-bot:latest
        environment:
            - LAVALINK_URI=http://lavalink:2333
            - LAVALINK_PASSWORD=lavalink
            - TOKEN=${TOKEN}
