[project]
name = "music-bot"
version = "2.0.0"
description = "Lavalink Discord music bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py[voice]>=2.5.2",
    "lavalink>=5.9.0",
]
